@echo off
setlocal enabledelayedexpansion

REM Run video-wall from Source on Windows
REM Auto-generated by universal build system

REM Set colors
set RED=[91m
set GREEN=[92m
set BLUE=[94m
set NC=[0m

echo %BLUE%[%TIME%]%NC% Starting video-wall from source (Windows)...

REM Check dependencies
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo %RED%[%TIME%] X%NC% Node.js is not installed
    pause
    exit /b 1
)

where npm >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo %RED%[%TIME%] X%NC% npm is not installed
    pause
    exit /b 1
)

REM Install dependencies if needed
if not exist "node_modules" (
    echo %BLUE%[%TIME%]%NC% Installing dependencies...
    call npm install
)

REM Run the app
if exist "package.json" (
    findstr /C:"electron:dev" package.json >nul
    if !ERRORLEVEL! EQU 0 (
        call npm run electron:dev
    ) else (
        findstr /C:"start" package.json >nul
        if !ERRORLEVEL! EQU 0 (
            call npm start
        ) else (
            echo %RED%[%TIME%] X%NC% No suitable run command found
            pause
            exit /b 1
        )
    )
) else (
    echo %RED%[%TIME%] X%NC% package.json not found
    pause
    exit /b 1
)

echo.
echo %GREEN%[%TIME%] OK%NC% Application session ended
pause
