#!/bin/bash

# Run video-wall from Source on Linux
# Auto-generated by universal build system

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] ✔${NC} $1"
}

print_error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ✗${NC} $1"
}

# Check if we're on Linux
if [ "$(uname)" != "Linux" ]; then
    print_error "This script is for Linux only"
    exit 1
fi

print_status "🚀 Starting video-wall from source (Linux)..."

# Check dependencies
if ! command_exists npm; then
    print_error "npm is not installed. Install with: sudo apt install npm"
    exit 1
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    print_status "Installing dependencies..."
    npm install
fi

# Set Electron flags for Linux
export ELECTRON_FORCE_WINDOW_MENU_BAR=1
export ELECTRON_TRASH=gio

# Run the app
if [ -f "package.json" ] && grep -q "electron:dev" package.json; then
    npm run electron:dev
elif [ -f "package.json" ] && grep -q "start" package.json; then
    npm start
else
    print_error "No suitable run command found in package.json"
    exit 1
fi

print_success "Application session ended"
