#!/bin/bash

# Run video-wall from Source on macOS
# Auto-generated by universal build system

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] ✔${NC} $1"
}

print_error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ✗${NC} $1"
}

# Check if we're on macOS
if [ "$(uname)" != "Darwin" ]; then
    print_error "This script is for macOS only"
    exit 1
fi

print_status "🚀 Starting video-wall from source (macOS)..."

# Check dependencies
if ! command_exists npm; then
    print_error "npm is not installed"
    exit 1
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    print_status "Installing dependencies..."
    npm install
fi

# Run the app
if [ -f "package.json" ] && grep -q "electron:dev" package.json; then
    npm run electron:dev
elif [ -f "package.json" ] && grep -q "start" package.json; then
    npm start
else
    print_error "No suitable run command found in package.json"
    exit 1
fi

print_success "Application session ended"
